# CrunchieMunchies

You work in marketing for a food company <b>myCorps</b>, which is developing a new kind of tasty, wholesome cereal called <b>CrunchieMunchies</b>. 

You want to demonstrate to consumers how healthy your cereal is in comparison to other leading brands, so you’ve dug up nutritional data on several different competitors.

Your task is to use <em>NumPy statistical calculations</em> to analyze this data and prove that your <b>CrunchieMunchies</b> is the healthiest choice for consumers.






# Task STEPS


1.First, import numpy.

In [1]:

import numpy as np


2.Look over the <b><em>cereal.csv</em></b> file. This file contains the reported calorie amounts for different cereal brands. Load the data from the file and save it as <b><em>calorie_stats.</em></b>



In [4]:

calorie_stats = np.array([70, 120, 70, 50, 110, 110, 110, 130, 90, 90, 120, 110, 120, 110, 110, 110, 100, 110, 110,
                          110, 100, 110, 100, 100, 110, 110, 100, 120, 120, 110, 100, 110, 100, 110, 120, 120, 110,
                          110, 110, 140, 110, 100, 110, 100, 150, 150, 160, 100, 120, 140, 90, 130, 120, 100, 50, 50,
                          100, 100, 120, 100, 90, 110, 110, 80, 90, 90, 110, 110, 90, 110, 140, 100, 110, 110, 100, 100, 110])

calorie_stats


array([ 70, 120,  70,  50, 110, 110, 110, 130,  90,  90, 120, 110, 120,
       110, 110, 110, 100, 110, 110, 110, 100, 110, 100, 100, 110, 110,
       100, 120, 120, 110, 100, 110, 100, 110, 120, 120, 110, 110, 110,
       140, 110, 100, 110, 100, 150, 150, 160, 100, 120, 140,  90, 130,
       120, 100,  50,  50, 100, 100, 120, 100,  90, 110, 110,  80,  90,
        90, 110, 110,  90, 110, 140, 100, 110, 110, 100, 100, 110])

3.There are <em>60 calories per serving of CrunchieMunchies</em>. How much <b>higher</b> is the <b>average calorie count</b> of your competition?

Save the answer to the variable <b>average_calories</b> and print the variable to the terminal to see the answer.


In [5]:

average_calories = np.mean(calorie_stats)
average_calories


106.88311688311688

4.Does the <b>average calorie count</b> adequately reflect the distribution of the dataset? Let’s sort the data and see.

<b><em>Sort</em></b> the data and save the result to the variable <b>calorie_stats_sorted</b>. Print the sorted data to the terminal.


In [6]:

calorie_stats_sorted = np.sort(calorie_stats)
calorie_stats_sorted


array([ 50,  50,  50,  70,  70,  80,  90,  90,  90,  90,  90,  90,  90,
       100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 110, 110, 110, 110, 110, 110, 110, 110, 110,
       110, 110, 110, 110, 110, 110, 110, 110, 110, 110, 110, 110, 110,
       110, 110, 110, 110, 110, 110, 110, 120, 120, 120, 120, 120, 120,
       120, 120, 120, 120, 130, 130, 140, 140, 140, 150, 150, 160])

5.Do you see what I’m seeing? Looks like <b><em>the majority of the cereals are higher than the mean</em></b>. Let’s see if the <b>median</b> is a better representative of the dataset.

Calculate the median of the dataset and save your answer to <b><em >median_calories</em></b>. Print the median so you can see how it compares to the mean.

In [12]:

median_calories = np.median(calorie_stats)
median_calories


110.0

6.While the median demonstrates that <b><em><q>at least half of our values are over 100 calories</q></em></b>, it would be more impressive to show that a significant portion of the competition has a higher calorie count that CrunchieMunchies.

<b>Calculate different percentiles</b> and print them to the terminal until you find the lowest percentile that is greater than 60 calories. Save this value to the variable <b>nth_percentile</b>.


In [17]:

nth_percentile = np.percentile( calorie_stats, 4, axis = 0 )
nth_percentile


70.0

In [32]:

nth_percentile = np.percentile( calorie_stats, 25, axis = 0 )
nth_percentile


100.0

In [33]:

nth_percentile = np.percentile( calorie_stats, 50, axis = 0 )
nth_percentile


110.0

In [36]:

nth_percentile = np.percentile( calorie_stats, 75, axis = 0 )
nth_percentile


110.0

In [37]:

nth_percentile = np.percentile( calorie_stats, 100, axis = 0 )
nth_percentile


160.0

7.While the percentile shows us that<b><em><q>the majority of the competition has a much higher calorie count</q></em></b>, it’s an awkward concept to use in marketing materials.

Instead, let’s calculate the percentage of cereals that <b><em><q>have more than 60 calories per serving</q></em></b>. Save your answer to the variable <b><em>more_calories</em></b> and print it to the terminal

In [68]:

np.where(calorie_stats > 60)


(array([ 0,  1,  2,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
        35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
        52, 53, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70,
        71, 72, 73, 74, 75, 76], dtype=int64),)

8.Wow! That’s a really high percentage. That’s going to be very useful when we promote CrunchieMunchies. But one question is, <b><em>how much variation exists in the dataset? </b></em></q>Can we make the generalization that most cereals have around 100 calories or is the spread even greater?

Calculate the amount of variation by finding the <b><em>standard deviation</em</b> Save your answer to <b><em>calorie_std</em></b> and print to the terminal. How can we incorporate this value into our analysis?

In [67]:

calorie_std = np.std(calorie_stats)
calorie_std


19.35718533390827

9.Write a short paragraph that sums up your findings and how you think this data could be used to 
<b>myCorp’s</b> advantage when marketing CrunchieMunchies.


In [14]:
print('There are many benefits regardless of whether you are marketing to businesses or consumers.')
print('As low calories in cereals are best for weight loss. ')
print('According to my calculations, cereal seems to be effective for weight loss and can be rich in fiber and nutrieants.')

There are many benefits regardless of whether you are marketing to businesses or consumers.
As low calories in cereals are best for weight loss. 
According to my calculations, cereal seems to be effective for weight loss and can be rich in fiber and nutrieants.
